### ISSUE TITLE
NULL handling

### ISSUE THREAD

**Issue by norv** [elkarte/Elkarte#135]
Add NULL handling to $smcFunc.

Example issue to address by handling NULLs by default:
https://github.com/elkarte/Elkarte/pull/134

**Comment by joshuaadickerson** [comment]
I don't understand the issue. Add IFNULL() to queries?

**Comment by Spuds** [comment]
Or make sure the db queries do not return NULL values for columns, but only 0's or empty strings?

Part / all of that could be handed by that test function I did (and I think now lost LOL) some time back which cast all the query return values to what the db structure defined (ints are ints, floats are floats instead of everything as strings)

**Comment by emanuele45** [comment]
@Spuds if you find again the code feel free to share! :P

**Comment by Spuds** [comment]
I think this is what I was babbling about: https://gist.github.com/Spuds/8dfc734cb545722fa18d
