### ISSUE TITLE
unable to switch default language

### ISSUE THREAD

**Issue by eurich** [elkarte/Elkarte#1527]
Sorry, can't give much details yet but it's impossible to switch the default language to another one ..  (tested with a german language pack)
Settings.php seems fine but the Interface still says english is Default.

**Comment by emanuele45** [comment]
I can think of a situation where it may happen: if you saved your profile.
When you save the profile account page, the language is written to the member's profile record, and from that point on this is the language the member will always see because the personal choice overrides the forum-wide setting.
