### ISSUE TITLE
Mentions and notifications

### ISSUE THREAD

**Issue by Ant59** [elkarte/Elkarte#1553]
Looking around an Elkarte forum, "mentions" and "notifications" are terms that seem to get used interchangeably.

Can we be a little stricter about this? **Notifications** should appear in the menu at the top and have a page where they are listed. Types of notifications _include_ replies (to watched topics), **mentions**, etc..

**Comment by emanuele45** [comment]
I'm not sure if it's correct to talk about it here or if open a new issue was a better idea, anyway I'm going here just to avoid spread the discussion over too many issues.
This is partially related to what @vekseid and @targren discussed in #1968 

I started looking into a more consistent and "centralized" notifications system (yeah, I know, I'm not really the best person for this task because I change my mind every two seconds and all that, but that's it).
Actually, even while working on #1950 I was already trying to head that way, but then I stopped just to have the code merged. Now I'm going back to that.
My current idea is:
* use modules to "hook" into the actions with the mention system
* the mention system loads the enabled mentions and decides if there is some kind of mention to be issued
* if there is any, it enters a record into a db table
* a scheduled task (that would be a task running each minute or so) checks if there is any notification in the queue to send (I decided to follow the scheduled task way just because if too many "mentions" want to send notifications it may be a pain, but anyway that may be tweaked)
* if the scheduled task finds something, it process the request and sends the notification.

The way I'm designing it, the options are:
* no notification at all
* notification (in the form of entry in the mentions/alerts area)
* notification + immediate email
* notification + daily email

I took inspiration from the way WBB handles the preferences, because it seems to make most sense.

In terms of "end-developers", that would mean (unless I'll do something stupid at some point) they have to write a single class with few public methods and the system will take care of everything else.
I started few hours ago, so it's still too early to show any code, but at least you know there is something going on.

**Comment by emanuele45** [comment]
I'm not sure if it's correct to talk about it here or if open a new issue was a better idea, anyway I'm going here just to avoid spread the discussion over too many issues.
This is partially related to what @vekseid and @targren discussed in #1968 

I started looking into a more consistent and "centralized" notifications system (yeah, I know, I'm not really the best person for this task because I change my mind every two seconds and all that, but that's it).
Actually, even while working on #1950 I was already trying to head that way, but then I stopped just to have the code merged. Now I'm going back to that.
My current idea is:
* use modules to "hook" into the actions with the mention system
* the mention system loads the enabled mentions and decides if there is some kind of mention to be issued
* if there is any, it enters a record into a db table
* a scheduled task (that would be a task running each minute or so) checks if there is any notification in the queue to send (I decided to follow the scheduled task way just because if too many "mentions" want to send notifications it may be a pain, but anyway that may be tweaked)
* if the scheduled task finds something, it process the request and sends the notification.

The way I'm designing it, the options are:
* no notification at all
* notification (in the form of entry in the mentions/alerts area)
* notification + immediate email
* notification + daily email

I took inspiration from the way WBB handles the preferences, because it seems to make most sense.

In terms of "end-developers", that would mean (unless I'll do something stupid at some point) they have to write a single class with few public methods and the system will take care of everything else.
I started few hours ago, so it's still too early to show any code, but at least you know there is something going on.

**Comment by emanuele45** [comment]
See #2049 
Still quite a bit of work to do though.

**Comment by JoeMoer** [comment]
Apologies if this is not the correct area, but I want "Notifications" turned on by default for all new posts but for the life of me cannot find where to enable that option for all users?  Could someone kindly point me in the correct direction please?

**Comment by Spuds** [comment]
I'm going to close this as the majority of work has been done.  

I will say that some additional cleanup in the code, mainly function names / comments, is required as some still have this inconsistency which leads to confusion when you work in that area.  Those are fix as found/required.
