### ISSUE TITLE
Please add some basic SEO features

### ISSUE THREAD

**Issue by axisdos** [elkarte/Elkarte#1898]
Hey guys, so far I really love this forum software because its functionality and design. However, what stopped me from using it is that it's missing some basic SEO features such as url friendly (domain.com/this-is-a-seo-url-friendly), auto generate meta description, and rel=nofollow for subpages on posts and forums. Thanks

**Comment by Vekseid** [comment]
Rather than rel=nofollow, it's better for SEO purposes to avoid presenting the link entirely to search engines where possible.

**Comment by joshuaadickerson** [comment]
@Vekseid, can you show where you get that from? I'd imagine you'd lose points for not showing the search engine the same as if it were a regular user.

**Comment by Vekseid** [comment]
You want search engines to have at least the same access that guests do, yes.

When Google sees a nofollow link, it still subtracts from the weight given to all other links on the page, however. Since these are likely to be much more important, it's best from both Google's perspective and yours that links that cannot be meaningfully followed (for example, profile links if guests can't see profiles) should not be shown, to guests or search engines, at all.

**Comment by emanuele45** [comment]
@axisdos meta descriptions are already present in boards and topics using the board name and the topic name, what would you suggest to use instead? :smile:

**Comment by emanuele45** [comment]
Apparently what is asked is already present (apart from friendly URL that are a 2.0 goal I guess), so I suppose we can close this one?

**Comment by Bench46** [comment]
SEO is a great method to make your website search engine friendly but this technique takes time to show the results so I think one must consider other techniques too along with SEO. Google [Adwords Management](http://visiblefactors.com/ppc-sem-campaign-management/) service works best.
