### ISSUE TITLE
Backport At.js fix for beginning of line in WYZ mode?

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#1948]
The bug is that when in WYZ mode, if you mention someone at the beginning of a new line the droppy doesn't appear.
Detailed explanation of the reason is [here](https://github.com/ichord/At.js/issues/209#issuecomment-65726892).

Applied fixes are:
https://github.com/ichord/At.js/commit/e1f65668e311c06d845164c49f303fdb6093cca6
https://github.com/ichord/At.js/commit/9b6465d848c6f5a0363c2c5f9bd99c2be741572c

Update At.js for 1.0.3 seems a bit too much, but the backport should be worth.

**Comment by emanuele45** [comment]
The backport is not really possible because we are way behind (we are using 0.4 while At.js is 1.0.1 at the moment.
We could apply the "trick" I found:
https://github.com/ichord/At.js/issues/209#issuecomment-65726892
but I have no idea of the consequences...

**Comment by Spuds** [comment]
I knew we were behind on that, I had not messed with it since it changed the way it detected, or does not, the iframe so it affects a few areas.  

If the "official" changes can't be used or backported (did that much change for that area?), we could certainly try your fixes on the site for a bit as a test.  I don't see how they can make things any worse TBH (they seem safe) and in 1.1 we will be on the new branch of AT anyway so it may be the best short term fix.

**Comment by emanuele45** [comment]
After a quick test of my workaround, it seems it work **sometimes**, not always.
To test with more browsers.
Better move to 1.0.4

**Comment by emanuele45** [comment]
Honestly I think it's better wait for 1.1 and upgrading the whole package.
