### ISSUE TITLE
Cache Class enable/disable

### ISSUE THREAD

**Issue by joshuaadickerson** [elkarte/Elkarte#2106]
The cache class needs two methods to: enable() and disable() so you don't have methods running around with parameters like $force. Just disable the cache before you call the method and re-enable it when you are done.

**Comment by joshuaadickerson** [comment]
With that, we should change $_cache_enable to $_cache_level and make $_cache_enable whether caching is enabled or not.

**Comment by joshuaadickerson** [comment]
Ugh, I forgot isCacheEnabled() and getCacheLevel()

**Comment by emanuele45** [comment]
Darn, I forgot about that.... :-\

Recently a bug was related to the enable flag: quick_get() is a bit of a pain, because it didn't run the callback if the check for enabled/disabled is done at the beginning of the method (just a reminder).

Anyway, the two methods are a good idea, I'll tag 2.0 not to break other things... :-\
