### ISSUE TITLE
Impossible to call addon action controller via integrate_actions

### ISSUE THREAD

**Issue by Ant59** [elkarte/Elkarte#2165]
Due to the format of the SiteDispatcher.class.php's actions array, it's not possible to call an action controller outside of the sources directory in Elkarte's core. The format needs to be changed to simply be a call to a class and method which the autoloader should take care of. This would make it possible to keep addons in their own directory under the "addons" directory.

This is the current format of the actions array.

https://github.com/elkarte/Elkarte/blob/development/sources/SiteDispatcher.class.php#L132
```PHP
// Format:
		// $_GET['action'] => array($file, $class, $method)
		$actionArray = array(
			'activate' => array('Register.controller.php', 'Register_Controller', 'action_activate'),
```

I propose this format instead:

```PHP
// Format:
		// $_GET['action'] => array('\\Full\\Path\\Class', 'action_method')
		$actionArray = array(
			'activate' => array('Register_Controller', 'action_activate'),
```

This would allow for additions to the array in the form of this for addons:

```PHP
			'page' => array('\\Elkarte\\Addon\\Pages\\Pages_Controller', 'action_index'),
```

**Comment by emanuele45** [comment]
In theory (I guess it's not written anywhere :blush: ), the actionArray is something in the process of being phased out, replaced by naming pattern and autoloading.

It would be cool to find a way to let the block at: https://github.com/elkarte/Elkarte/blob/development/sources/SiteDispatcher.class.php#L212 find out about addons and load automagically them, though at the moment I'm not sure how to do it. :-\
Well, if we can't find a way, I guess actionArray could it at least for now. :D

**Comment by Ant59** [comment]
I can see how that could work, but naming conflicts may arise between addons, which namespaces would remove. However, of course that then introduces the need for namespaces in the URL, which is messy, and that brings us back to Elkarte mapping actions to controllers :/ Not sure how to get around that.

**Comment by emanuele45** [comment]
Sorry, I failed to mention, but namespacing was part of my flow of thoughts. :)

One way (but that may be a little too restrictive) could be to match:
```
?action=myaction
```
to two possible namespaces:
```
ElkArte\Controller\Myaction
```
pointing to ```CONTROLLERDIR```, and
```
ElkArte\Addon\Controller\Myaction
```
pointing to ```ADDONSDIR/Myaction/Controller```.
Then it would be a matter of testing the class_exists on the two namespaces:
```
class_exists('ElkArte\\Controller\\Myaction\\Myaction_Controller');
class_exists('ElkArte\\Addon\\Controller\\Myaction\\Myaction_Controller');
```
and you are almost sure to pick the correct one (addons may have precedence over "core" controllers (so first check for addon, then for core) so that an addon could entirely replace an existing controller.

yeah, double work for the autoloader and filesystem... :-\
Thought and random ideas, nothing more. ;)

**Comment by Ant59** [comment]
Oooo I see! I like it. Not sure if I'm misunderstanding, but it seems you missed a directory level in the namespace for the name of the addon. Would you not have to check for a controller in all the installed addons?

**Comment by emanuele45** [comment]
That was the "little too restrictive" part: it would mean limit each addon to a single action...
Or, otherwise, mimic the actionArray defining matches action => namespace:
```
       'page' => '\\Elkarte\\Addon\\Pages\\Pages_Controller',
```
that is basically what you suggested (except it delegates to the controller how to deal with sub-actions), so I guess you are right. xD
