### ISSUE TITLE
URLs followed with a bracket and period have the bracket and period included in the generated link

### ISSUE THREAD

**Issue by Ant59** [elkarte/Elkarte#2171]
For example, if I write the following and post it to the Elkarte community forum:
```
blah blah blah (https://example.com/example).
```

Then the generated HTML will be:
```
blah blah blah (<a href="https://example.com/example)." class="bbc_link" target="_blank">https://example.com/example).</a>
```

I don't know what other symbols this affects.

**Comment by Spuds** [comment]
This is one of those :difficult ones to fix ... the problem is that ``` ( ) . ```  (among others) are valid symbols of a url.  So you and I can look at that and understand the intention, but a filter will simply see the http(s)? bla and see the symbols as valid syntax and include them.  

Its typically only the wrapping in ()'s that is the problem so you could potentially look to see if there is a leading ( ahead of the http and then it ends in a ) and drop them,

**Comment by Ant59** [comment]
I see what you mean looking at the RFC that defines URI characters. That's a pain :unamused: 

That sounds like a suitable solution. I think that wrapping URLs in () is quite common when people want to refer to a link on what they're talking about.

**Comment by Spuds** [comment]
Here is the proposal https://github.com/elkarte/Elkarte/commit/97ff437319f0891de5578336412e8b7ec83a7422

The alternative is to no allow links with () in the path area as well.  Would break some autolinks but autolinks is a "goodie" and you can always use URL syntax.  Downside to this is that we have allowed them to work up to this point, so its a bit of poor form to break it now, although I get they have never been needed, its a bit rare.

**Comment by emanuele45** [comment]
@Spuds did I got it right that the commit was in one of your previous PRs?

**Comment by Spuds** [comment]
Yup ... I did the if it starts with a ( then the result is rtrim ')' . ')' so should be fixed.  Of course there are other edge cases that will not get caught ... like (link). (trailing .) but its an incremental improvement for now.
