### ISSUE TITLE
Update Font Awesome 

### ISSUE THREAD

**Issue by wintstar** [elkarte/Elkarte#2186]
Meanwhile there are now Version 4.4.0 with more icons.

http://fortawesome.github.io/Font-Awesome/whats-new/

**Comment by emanuele45** [comment]
It seems a task for 1.1, what do you think?

**Comment by wintstar** [comment]
It would not be a big hassle, so I guess so for 1.0.5.

**Comment by Spuds** [comment]
Should be a straight replace of the webfonts and single css file, so its safe for 1.0.5   We are at 4.2

Another item, I *think* the combiner understands .min.css (I know it does .min.js) ... if so we should be using the .min from the distro 

Not pressing for 1.0.5 since only addons would use the new icons, but safe should we want to remain current.

**Comment by Spuds** [comment]
If we want it for 1.0.5 .... https://github.com/elkarte/Elkarte/pull/2194

Updated it to use the .min package as well.
