### ISSUE TITLE
Inline Attachment Helptext not display

### ISSUE THREAD

**Issue by wintstar** [elkarte/Elkarte#2189]
New Install last pull request #2173 from emanuele45/fix_psql

This version: ElkArte 1.1
Current version: 1.0.4 bug fix update
MySQL version: 5.6.25
PHP: 5.6.11

Administrations Center => Attachment Settings. When setting Inline attachment settings missing the icon question mark around the text of Help.english.php line 654 to display.

Change
$helptxt['attachmentInLine'] = '<b>Add an inline attachment</b><br />
to
$helptxt['attachment_inline_title'] = '<b>Add an inline attachment</b><br />

![attachment-helptext a](https://cloud.githubusercontent.com/assets/2753863/9449850/96b1e316-4aa5-11e5-807e-c710c9901545.PNG)
![attachment-helptext b](https://cloud.githubusercontent.com/assets/2753863/9449853/9891dd76-4aa5-11e5-83b2-736ee17c0451.PNG)

**Comment by emanuele45** [comment]
I'm not sure there is any help text (I didn't check TBH), in case it's missing it should be written before adding the icon I guess.

**Comment by emanuele45** [comment]
Next time I should read more carefully the report... sorry!
Anyway, the help text is largely outdated because still referring to the way the addon deals with ILA, while the "core" feature has been changed quite a bit.
For the moment I'm not sure an help text is **really** necessary. We can add it later.
