### ISSUE TITLE
Inline Attachment .css missing

### ISSUE THREAD

**Issue by wintstar** [elkarte/Elkarte#2201]
Forum-Version: ElkArte 1.1
Aktuelle Version: 1.0.4 bug fix update

CSS instructions missing, see https://github.com/Spuds/Elk_Inline_Attachments/blob/1787d2bbd07909cb98d723b9229b40a481bfab0e/ILA.css. In Blue Feeling I inserted the CSS instructions. In the header of the style can be changed.

Look at here http://elkarte.scaricare.de/110/index.php?topic=3.0.

**Comment by emanuele45** [comment]
Auch!
I guess I forgot to add it to the commit... LOL

**Comment by emanuele45** [comment]
@Spuds I'm a bit lost, how did you do the align stuff in ILA? :confused: 
I can't see the parameters in the bbcode, did you do some other replacements somewhere?

**Comment by Spuds** [comment]
Going from memory here so beware ! 

I thought the function ran post BBC so does not really depend on parseBBC :/ 

It searches for [attach= .........] and does its own parsing inside of the ila function itself.  It should look for type, align and width parameters and set the class / replacement as needed.  I *think* I had to do it that way to handle those friggin quote issues (since it does not render inside a quote, only links inside of a quote)

**Comment by emanuele45** [comment]
Ohh... okay, makes sense.
Well, the new tag is using the bbc parsing and doesn't really have any option at the moment, so I guess we can move this to beta 2/3 waiting to add back what is missing. ;D

**Comment by emanuele45** [comment]
At the moment, the img uses the same css of normal images embedded into the text.
It looks enough for now (until we have better handling at least), so I'm closing this one.
