### ISSUE TITLE
Poll preview does not work

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2254]
Start a new poll and select preview, only the message preview is shown not the poll

Also does not work with editing a poll either, although I'm not sure it ever worked there.

May need a preview event trigger or other?

**Comment by emanuele45** [comment]
Daaarn... :-\

**Comment by Spuds** [comment]
Yeah .. noticed it doing my _req stuff.  Been trying to test the changes and doing that I could not find where the poll preview func was called at all :(

**Comment by emanuele45** [comment]
Without looking at the code, there are two possibilities:
1) the poll controller,
2) the PostPoll module.

**Comment by emanuele45** [comment]
Actually, I couldn't see any poll preview in any incarnation of the code, not even in its previous life...
Are you sure polls ever had a preview? :confused:

**Comment by Spuds** [comment]
Can't say for sure ... just saw the code that looked to be intend to allow the preview ... would not be the first partially implemented code we have found down in the bowls of the beast.

**Comment by emanuele45** [comment]
I did some tests: pool preview was present in SMF 1.1 but didn't actually do anything, then the button was removed in 2.0, but not the code.
So, now we have still the code, but no button and likely no template.

Either drop or implement it.
Implement it may be tricky now, because of the two ways to create a pool (adding it to the post form via ajax or adding it to an existing topic).
I'd say let's forget about it for now, and maybe implement it "properly" (ajax-ively I'd say with a proper sub-action and all the mumbo-jumbo) later, like in 2.0.

Or do you want to add it to 1.1? :angel:

**Comment by Spuds** [comment]
For 1.1 then I'd say drop the old "crud" that is left in the code.  Then for 2.0 we can add a feature request for that capability and debate it then.  To funny really!

**Comment by emanuele45** [comment]
Good, I'll use the PR already open for that! (Dropping that is.)

**Comment by emanuele45** [comment]
Just to be sure, I can only see a couple of lines of code related to previews: in edit2 the ```return $this->action_edit()``` and the ```if (!$this->_req->preview``` (or similar).
Did you see anything else?

**Comment by Spuds** [comment]
I don't remember :disappointed: It was when I was trying to figure out if things were post or get or the super hideous both.  I would then try to test the change and in this case it was one of those WTF moments.

**Comment by emanuele45** [comment]
Lovely moments! :dancers:
