### ISSUE TITLE
Search namespaces warning

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2255]
```Warning: class_implements(): Class \ElkArte\Search\API\sphinxql does not exist and could not be loaded in /var/www/sources/subs/Search/Search.php on line 127```

In that case sphinxql but seems to do it for all search API's ... also that case seems off .. not sure if we need to do a ucwords.

@emanuele45 If you could take a look at this one, its a namespace issue that I'm not immediately seeing.

**Comment by emanuele45** [comment]
hmm... I guess it's a "backward compatibility issue.
Your $modSettings['search_index'] contains "sphinxql" because "before"
that part was used. Now I set it to store Sphinxql_Search (i.e. the
name of the class), so it tries to
```
$a = new \ElkArte\Search\API\sphinxql
```

while it should do:
```
$a = new \ElkArte\Search\API\Sphinxql_Search
```

There are two solutions:
1) the dynamic one, checking each time if the class ends in "_Search"
and if not attach it,
2) the static one, changing the value in the database with upgrade.php

Which one do you prefer?

**Comment by Spuds** [comment]
Update it in upgrade if we can.  Don't want more Yabb support lines in the code :smile_cat:

**Comment by emanuele45** [comment]
Try moving:
```
		Elk_Autoloader::getInstance()->register(SUBSDIR . '/Search', '\\ElkArte\\Search');
```
to pre_dispatch.

**Comment by Spuds** [comment]
Didi not seem to help either problem (performing a search or managing search)

**Comment by emanuele45** [comment]
That's embarrassing... LOL
I'll have a deeper look, starting next week I'll be again more active
(at least during the weekend). :D
