### ISSUE TITLE
SMTP Password no longer being base64 encoded

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#2282]
Which naturally causes all sorts of shenanigans.

The culprit seems to be Spud's commit here:

https://github.com/elkarte/Elkarte/commit/ebf3b243408e3b4b76687af583d040447d62f87c

Moving away from abuse of $_POST is good, but it doesn't matter since Settings_Form::save_db still refers to $_POST.

The 'clean' solution here seems to be to make use of the 'post object' parameter in save_db, which is nearly as bad but should at least not cause regressions after a proper update.

**Comment by Spuds** [comment]
Sorry about that.  I know that some of the subs are still dependent on $POST stuffing :sob:  On the brig's side at least it was POST and not the abomination REQUEST.

I tried to do just about was you did in the PR.  In some cases I actually fully re-stuffed post (yes its awful) since the subs were so bad and noted the mess with @ todo so I would remember to try and fix the subs as well which gets dicey due to backwards compatibility with addons

Anyway step at a time, we will get them!
