### ISSUE TITLE
Maximum execution time

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#2321]
if my package is large size:

```
 Fatal error: Maximum execution time of 30 seconds exceeded in C:\apache\php\localhost\www\elkartest\sources\subs\Package.subs.php on line 1502
```

maybe add

```
set_time_limit(60*3);
```

**Comment by joshuaadickerson** [comment]
What package? Just set the time limit to be greater in a script in your package if you are running an operation that takes a long time.

**Comment by emanuele45** [comment]
Though, that page is a bit of a pain and can limit the number of packages around.
It may be worth considering some AJAX solution: run a scan on the directory to fetch the packages to load a minimum table (and know which packages are available), and then load the details via an ajax call for each package or a limited number of them. That way the load is spread among several requests and not a single one, reducing the odds of timeouts or other problems.
Okay, that's more for 2.0 though. lol

**Comment by KeiroD** [comment]
... I was wondering why Gmail marked this e-mail as important before I realized it was because I had set Github to notify me about conversations regarding Elkarte.

As far as maximum execution time... that's a php.ini issue. Please check your php.ini. Look for this setting: `max_execution_time = 30` and raise it to something like say... `120`. Experiment as necessary to find the sweet spot.

**Comment by joshuaadickerson** [comment]
@emanuele45 what makes this a bug? I don't see any issues.

**Comment by interlab** [comment]
Error unpacking the archive package due to time constraints of the script

**Comment by joshuaadickerson** [comment]
Ah, it can't open the tar.gz/zip fast enough? Which package?

**Comment by interlab** [comment]
zip file > 9mb

**Comment by emanuele45** [comment]
More than 30 seconds to load a page is not a bug?
To me it's something pretty annoying that we should improve.

**Comment by interlab** [comment]
not bug

**Comment by KeiroD** [comment]
@emanuele45 No, it's not a bug. The issue is that @interlab did not raise the maximum time execution limit for `PHP`.

I provided the fix. It's literally that simple. There is no bug here because you're going to encounter the same problem until you implement the fix I provided on the server itself.

It's a server-side issue not an `Elkarte` issue.

**Comment by Spuds** [comment]
2.0 raised the time limit, of course the sites php.ini has to allow for greater times.
