### ISSUE TITLE
Add a way to test email settings

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2355]
> I think there should be a link on the managemail page to send a test email to ensure you've set it up correctly. I'm kind of concerned that I might not have it setup correctly.

**Comment by emanuele45** [comment]
I was looking at that one, though it's a bit tricky I think, more because of the expected behaviour.
What I was thinking to do was a link (along the lines of "clean hives") with (maybe) an AJAX call to send the email in background.
Though, I feel it would look odd: in this condition I would expect the setting I just entered (either saved or not) to be the ones used for the sending. But, using unsaved setting would be... confusing, because then it could lead to people not saving the settings (forgetful people like me for example :angel: ).

Could the solution be to save the settings while sending the test email? Informing the admin, of course.

**Comment by Spuds** [comment]
Probably save on send ... actually I think we have the same condition on the Sphinx search settings .. if you try to connect to the search daemon without first hitting save, it will fail.  This even though the fields are populated with some defaults, those defaults are not in the DB yet.

**Comment by emanuele45** [comment]
I'm tempted to move it to 2.0

**Comment by Spuds** [comment]
I think there are a few things that would have to be done .. new test template, testing all of the replacement fields, including pbe,  etc etc ... moving it to 2.0 as I don't see us doing this

**Comment by Spuds** [comment]
Added a basic email form in the ACP that an admin can use to send ... pretty basic implementation for a start.
