### ISSUE TITLE
1.1 boards icon doesn't turn to "read" (i.e. grey)

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2397]
Looks like the css is a little broken, the ```board_icon off_board``` (board index, board marked as read) has still the green icon instead of the grey one (I'm talking about the light variant).

**Comment by Vekseid** [comment]
I'll take this, if there's no objection to me doing an embedded icon solution (per #2375)

**Comment by emanuele45** [comment]
No objections from me.

**Comment by Spuds** [comment]
Could you post an example of what the code would look like?  Like today to use fa I'd do 
```<i class="fa fa-check></i>``` what does that become ?

**Comment by Vekseid** [comment]
&lt;i class="icon i-check&gt;&lt;/i&gt;

I'm using i to reflect the fact that I'm doing things like declaring color, fills, strokes, etc. in the embedded declaration, so it's not the exact same.

There are some pseudo-limitations.

Non-square icons that we can't just let be square will need special treatment.

Because of the nature of it, it can't just be stuffed on as a prefix, i.e.

&lt;i class="icon i-check&gt;imagine this is a list and you want the icon prefixing it&lt;/i&gt;

Won't work, since the icon class needs to be a fixed size in proportion to the embedded svg's viewport. Also, it breaks IE7 support (for as long as we may care about that).

Both of these are pretty trivial though.

**Comment by Spuds** [comment]
Had not considered the pseudo implications .. today we use font-face = font awesome + content = some hex code to add icons in a few places.  Could you expand on what limitations we need to work around?

As for ie7, we don't support that and in 1.1 ie8 is also not supported ... not supported as in there are no specific work around in place (also since 1.1. is JQ 2.0 and ie8 support went away there as well)

**Comment by Vekseid** [comment]
It works pretty much the same way, except it's just content=svg image.

`.i-undisclosed::before {
	content: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' stroke='black' stroke-width='6em' fill='transparent' viewBox='0 0 4096 4096'%3E%3Cpath d='M2816 2432q0-370-263-633t-633-263-633 263-263 633 263 633 633 263 633-263 263-633z m256 0q0 234-91 447t-246 368-368 246-447 91-447-91-368-246-246-368-91-447 91-447 246-368 368-246 447-91 447 91 368 246 246 368 91 447z'/%3E%3C/svg%3E");
}`

However, the icon needs to specify a fixed and, in this case square size. The only 'issue' I've noticed so far is I'll need to work something out for the totop and tobottom icons. I don't see you putting content inside tags anywhere (though we can and probably should put accessibility content in there).

**Comment by Spuds** [comment]
Thanks for those details, it helps.   So we just have to specify pseudos with data url's, I like those myself.

Just thinking out loud (yes i know, sorry), but to make things easy to "theme" should we have all of those SVG items, maybe in a separate css file inside the variant directory?  

Just thinking that is someone wanted to use other than the font awesome icons, and used your font ripper to create the SVG's from another font library, it would be nice to be able to go to one file and make the adjustments. Don't know if thats plausible or not, just a thought since it feels like we are defining our own 'fa' class that we can feed with whatever SVG we like.

**Comment by Vekseid** [comment]
I'm putting the icons in the _light file partly for this reason. They've got their own section and are eating other sections as things get simplified.

Splitting them out is an option, but it's trivial. We can see what theme creators prefer, but this is going to be vastly streamlined over prior incarnations of SMF and Elkarte.
