### ISSUE TITLE
1.1-dev shows users as being logged in forever

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#2413]
At least while using database sessions.

**Comment by Vekseid** [comment]
I am not sure what is going on with this one. There doesn't seem to be anything that gets rid of old log_online entries?

**Comment by emanuele45** [comment]
Do you mean in the who-is-online page?

**Comment by Vekseid** [comment]
Everywhere - whether or not someone is 'online'. Their is_online property is true.

No proper pruning of the log_online table seems to be occurring and that is where the software is getting the is_online status from.

**Comment by emanuele45** [comment]
The issue is in:
```
$do_delete = $cache->getVar($do_delete, 'log_online-update', 30) && (int) $do_delete < time() - 30;
```
if cache is disabled getVar returns false, so $do_delete is never true and the log_online never cleaned up.
If I'm not completely :sleeping: I think in this case test if the cache was hit is useless, jsu:
```
$do_delete = $cache->get('log_online-update', 30) < time() - 30;
```
should suffice:
* cache enabled a value is returned and compared to the last 30 seconds gap,
* cache disabled an equivalent to 0 is returned and the delete will always be applied.
