### ISSUE TITLE
Why is this marked depreciated?

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2521]
public function action_spellcheck()

What is the new method?

**Comment by emanuele45** [comment]
By the look of the function, I'd say the intention is to call ```?action=spellcheck``` that should directly start the spellcheck controller instead of passing through post.
Of course, this won't happen for the moment because $actionArray overrides the naming scheme, but at least is how I was thinking it should behave (see 659eff7faf5dccab9b0e5907500f9da15806a363 )

**Comment by Spuds** [comment]
Ah .. perhaps better as a todo then?  To me depreciated means do not use it, certainly not in the core, and its only been left in place for addon support

**Comment by Spuds** [comment]
37fc3da7735e0044e3131ae0e7422ca7f25123b0
