### ISSUE TITLE
Due to IE's 2083 character limit

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#2530]
There are few places where some parameters in the url are gzipped to workaround a limitation in "old" versions of IE.

From MS KB:
https://support.microsoft.com/en-us/kb/208427
the limitation is for IE <= 8.

I seem to remember we are not going to support IE8 in 1.1, so these tricks can probably be dropped?

**Comment by Frenzie** [comment]
I dunno, not caring whether it gets the full experience is a bit different
from not working at all. But when would you ever see a URL that long in
Elk/SMF?

**Comment by Frenzie** [comment]
Link to code: https://github.com/elkarte/Elkarte/blob/f35fd546fa008f27e2137b80a3e6eb4d1a0e9ac4/sources/subs/Search/Search.php#L617

I'm not sure I follow. Aren't searches POST rather than GET? I mean, you can "hack" the search by appending `&search=lala` but that wouldn't be affected by this one way or the other. Basically unless I'm missing something (NB I haven't exactly been looking!) this seems utterly worthless regardless how old your IE.

**Comment by Vekseid** [comment]
Searches are get requests. They don't change anything in the database.

**Comment by Vekseid** [comment]
Derp.

Why are searches POST anyway?

**Comment by Frenzie** [comment]
They definitely are POST requests and indeed they don't but that has nothing to do with it. =)

**Comment by Frenzie** [comment]
Hm, actually… the links to the next page of course aren't.

So the question is really why the search FORM does a POST instead of a GET.

Alright, so get rid of the silly IE thing (I mean, seriously, who searches for 1800+ character strings anyway even if IE6 were still in active use?) and change the search template stuff to GET?

**Comment by Frenzie** [comment]
D'oh, answered my own question. It does a POST to avoid the IE bug on submit and then it uses the gzip to avoid it for the links. But yeah, the whole thing strikes me as wtf. xD

**Comment by emanuele45** [comment]
Yeah, I guess it's never so many characters, even considering all the name of the elements of the form... tested it out, the "base" (i.e. with no search string) is 200 characters long.
Though, looking at the code, it does some other nasty things that may actually be replaced by a simple json_encode...

**Comment by Spuds** [comment]
I'll call this partially addressed, well at least all the pre php 4.3.9 cruft was removed and its now using json_encode

The char limit item is still in place, mainly since I do not understand the entire history, but madness like that does not just appear unless someone did something ... practical, not really, would someone do it, oh 🔥 yes!
