### ISSUE TITLE
Text on email notification fon new PM

### ISSUE THREAD

**Issue by radu81** [elkarte/Elkarte#2568]
When receiving a notification by mail I get this text:

> �You have received a personal message from emanuele on ElkArte Community
> The message they sent you is:

.....

> Regards, The ElkArte Community�РХ�Sv63s6fC�f&C33CVFS3cSF&63��R��

**Comment by emanuele45** [comment]
@radu81 do you still get these emails?
I wonder how this report got lost for so long! :sob: 

BTW I guess it was 1.0, right?

**Comment by radu81** [comment]
on my live forum I disabled the content of message so I did not notced this. It was an error on elkarte.net forum when it was on version 1.0.x

I just enabled the content of private messages into email on my 1.0.10 forum and did a test. No strange characters are displayed. So I'd say it is solved.

**Comment by Spuds** [comment]
That was a result of the [hexkey] line, that we put in place since some clients strip the x-header, being encoded with base64 ... 

Pretty sure its all been fixed, but would appear in 1.1 only when special chars were present, then a base64 version of the email was created and our hex code was attempted to be un-encoded, producing giberish.
