### ISSUE TITLE
On new installations, do not display warning (missing Settings.php)

### ISSUE THREAD

**Issue by tomreyn** [elkarte/Elkarte#2610]
On the first installation of ElkArte 1.1.0 beta1, despite following the [documented installation steps](https://github.com/elkarte/Elkarte#setting-up-an-elkarte-forum) precisely, the following warning message displays:

> Warning!
> It looks like Settings.php and/or Settings_bak.php are missing from the default directory of your forum, ElkArte will try to rename the sample files provided with the installation. If this operation fails, please rename Settings.sample.php and Settings_bak.sample.php respectively to Settings.php and Setting_bak.php before running this script.

While this warning suggests that an unexpected situation (may have) occurred, this is actually the expected situation on a new installation. As such, I suggest to modify the behaviour of the install script in a way which either 

* does not display this warning on a first install (if this situation can be reliably detected, such as by a shipped-by-default lock file which is later removed - or its content changed - as part of a successful installation process)
* extends this warning to state that this situation is to be expected on a new installation
* downgrades the warning to a hint / note, i.e. replace the 'warning' icon by 'hint' icon, replace the yellow background by white or grey or similar.

Ideally, during a successful standard installation which does not run into any unexpected situations, a user should not get to see any warnings at all.

_Note:_ This is obviously just a very minor bug or feature request. I am unable to tag it as such, though.

**Comment by emanuele45** [comment]
Yeah, I know that one. :innocent: 

TBH, I put the warning, mainly because I couldn't decide what was the best way to deal with it and then I forgot about it. lol

My first idea, was to suggest in the documentation to rename the files before uploading them, so in theory the warning was not shown to people that renamed the files (so it was legit to say "pay attention, you didn't what was suggested, I'll try to fix your behaviour, but I may not be able to"), then I started wondering if it was really worth (people usually tend to avoid reading documentation, I know very well because I'm one of them :angel: ) and never put any real warning anywhere, but at the same time I also forgot to ask for opinions on the matter, and nothing moved. :crying_cat_face: 

Well, this is a good chance. :grinning:
