### ISSUE TITLE
integrate_actions hook: strange logic

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#2662]
Example:

my hook:
```
    public static function integrate_actions(&$actionArray, &$adminActions)
    {
        if (!self::$enable) {
            return;
        }
        
        code ...
    }
```

but this hook does not disconnect the call controller.
I have in the controller again checked whether an addon is enabled.

**Comment by emanuele45** [comment]
If you have:
```
action=something
```
and the controller is in a file named ```Something.controller.php``` and the class is ```Something_Controller``` then Elk doesn't use $actionArray. You just need the files.
So probably your integrate_actions is not even called.

**Comment by interlab** [comment]
I think it's weird :wink:

**Comment by emanuele45** [comment]
Well... the idea is to reduce the actionArray as much as possible and use it only to override the default behaviour.
The default behaviour is the naming scheme (what I explained earlier).
Now, the reason your code fails is that when your addon is not enabled the action is not added:
```
if (!self::$enable) {
    reutrn;
```
so, the check:
```
if (isset($this->actionArray[$this->action]))
```
fails, because there is no such action. The system thinks no functions are defined for the specific action and tries the alternatives (i.e. naming scheme). The file follow the naming scheme and so it is picked.
