### ISSUE TITLE
Fatal error - memcache

### ISSUE THREAD

**Issue by Trekkie101** [elkarte/Elkarte#2811]
Fatal error: Call to undefined method Memcache::setOption() in /home/dlrpr/public_html/forum/sources/subs/CacheMethod/Memcached.php on line 170

Apparently :/ from today's development branch.

**Comment by emanuele45** [comment]
Seems like the block of options is valid only for Memcached and not for Memcache.
@live627 you added them, can you confirm?

**Comment by Trekkie101** [comment]
I've done some digging for the last hour, it seems there is no comparable setOptions for memcache. Instead you'd use most of them during connection. 

I should add - this only occurs when going to the admin panel. The rest (public) side works. 

I think it's an old cPanel build my site was using - could potentially just drop support for memcache as anyone serious would be using memcached I'd think?

**Comment by Spuds** [comment]
Looks like we just need to update the code to properly support both.

**Comment by emanuele45** [comment]
I couldn't find similar settings for Memcache, something can be configured (server timeout and server retry interval), but they have to be set either when the server it added or **after**, while at the moment options are set **before** the servers are added.

**Comment by Spuds** [comment]
Agree there are none.   I think we have a few options

1) Remove the options section for Memcache and just let the defaults be what they are.  In 1.0 we just used the default values in ->connect or ->pconnect anyway.   But do note I don't see any pconnect in the new class.

2) Remove the section as above but "tweak" the values when doing the addServer for just Memcache (which allows for the options).  MemcacheD will use the options provided in setOption.  Do note the setOption values being used for MemcacheD are non default and having never used that engine I don't know whats good.  Part of me thinks since they are all hard coded values, just using default may be a better option but again, no real idea.

3) Drop the use of ->addServer and return to connect / pconnect.  This allows us to set some class constants for use in those functions for either Memcache/MemcacheD ... this would also address that the current class no longer supports perm connections AFAICT

**Comment by emanuele45** [comment]
Is the [persistent_id](http://php.net/manual/en/memcached.construct.php) equivalent to pconnect?
If so, then, I'd go with 1 and fix the persistent.

**Comment by Spuds** [comment]
Yes, "D" needs it in the constructor (persistent_id) , D-less needs it as part of setServer.  I've go a basic update that is along those lines done, tried to test it by installing Memcache and seems to have tanked my install, LOL ... once I get it running again i'll do a test.

**Comment by emanuele45** [comment]
> and seems to have tanked my install

what a wonderful moments are those! xD

**Comment by Spuds** [comment]
LOL ... well I got things running again 🍻 

I'm going to break these apart and have one for each engine.   There are several differences between the two interfaces and the class is simply getting littered with if/else constructs, so at a certain point you have to stop and go what am I doing !   

The last straw was that the ->set method is different between the two, one requires the expire as param 4 the other as param 3, that on top of needing to overwrite the title() method, the options, the setServer, etc

**Comment by Trekkie101** [comment]
Give me a nudge if you want access to mine that seems to have memcache installed?

**Comment by Trekkie101** [comment]
Good work @Spuds and @emanuele45 very quick fix.
