### ISSUE TITLE
?debug not working

### ISSUE THREAD

**Issue by cody3647** [elkarte/Elkarte#2829]
Adding ?debug to the URL does not seem to be working.  Chrome spits out an error message that changes depending on what page you try to view.  Followed by some part of the source code of the page.

> This page contains the following errors:
> error on line 251 at column 9: Opening and ending tag mismatch: br line 0 and p
> Below is a rendering of the page up to the first error.

> This page contains the following errors:
> error on line 45 at column 16: StartTag: invalid element name
> Below is a rendering of the page up to the first error.

Not working on my own test site or on the Elkarte site.

I checked all the places where $_GET['debug'] was in the code but couldn't find anything that changed (at least in relation to surrounding code since some moved to different files).

**Comment by Spuds** [comment]
This is a bit complicated I feel, or not, depends on what we really want or expect.

The history of ?debug was to enable a ```Content-Type: application/xhtml+xml; charset=UTF-8``` header.  This basically "turns on" xhtml processing in the browser, which is a "strict" standard, unlike plain html.   At one point SMF was xhtml compliant, so that ?debug was used to rigorously check things.

As you saw it generated a page failure right way, in the example given its because the page used ```<br>``` instead of ```<br />```, only the later is valid xhtml.  Actually we had decided early on that we would only use xhtml syntax but some "loose" html made its way in, so in a way that is a bug, or at least an inconsistency.  

If we fix the handful of self closing tags, there will still be issues with entities such as ```&nbsp;``` which is not valid xhtml, you instead have to use ```&#160;```   As a quick test I simply corrected those two issues in the output buffer, and then set the namespace to the html tag to ```xmlns="http://www.w3.org/1999/xhtml"``` and the page came right up.

Now I'm going to take a guess that you don't really give a crap if the page is xhtml compliant, and no one ever said ElkArte was xhtml compliant anyway.  But the other thing you used to get with ?debug were those template "ends" markers which could help determine which one you wanted to modify to add your content.

So what were you expecting from ?debug 

My thinking is we should a) fix our tags so the templates are consistent b) remove the sending of the xhtml header (on debug) since we are not, nor will be purely xhml compliant, c) fix the sub template start/end markers so they do work with ?debug

**Comment by emanuele45** [comment]
Actually, the most important (and up until after reading @spuds explanation I thought it was the unique) function of ?debug was the highlighting of the starting/ending of the layers (that was removed in 00e2572d2e82cfc5cdee7e1271ca63292805f373 ).
I would restored that one and scrap all the :hankey: about xhtml and alike. :angel:

**Comment by emanuele45** [comment]
Regarding the self-closing tags, to me one or the other is the same... really no strong feeling (even though I seem to remember that a while ago I thought they were better... but now it's more :man_shrugging: )

**Comment by Spuds** [comment]
I added the br => br / to the open PR that I have ... it fixed a bug in SSI which was ```strtr br``` for previews, but our parser still uses br / 

If/When we convert to dropping the /, we will have to change strtr to convert both br and br / to newlines or whatever
