### ISSUE TITLE
Security edits in images

### ISSUE THREAD

**Issue by sbulen** [elkarte/Elkarte#2874]
I hope it's not a breach of protocol to post this bug in two forks that share the same code...  

I'm a photo junkie.  Many of my photos are getting rejected in the other forum (I admit I haven't yet tried Elkarte).  I see you have the exact same code in the graphics subs module...   Which I think means you will also encounter the same false security fails.  

_This is pretty frustrating for users trying to use the forum to share photography._

In short, the preg_match checks in checkImageContents will find matches in many images.  In my experience, about 10-20% of large, hi-res photos are _erroneously_ failing security checks, even on things like 'body' and 'html'.   

We're losing a statistical battle.  In my mind, the image encoding is like the thousand monkeys typing away & accidentally writing Shakespeare's works.  Only they just have to get a hit on something like 'body' or 'html'...   In a big enough .jpg, odds are pretty good that happens.  

I'd be interested in knowing the best approach to fix - for both forums.   My proposed solution has evolved as I have learned more over the last couple of weeks.   Currently, my thinking is to not do the preg_match checks AT ALL if the image is to be re-encoded.  The re-encoding should clean it up and strip out malicious strings.  I'd like to know if you agree.  If so, the fix is easy.  

==========

An aside: one minor issue with the 'extended' search string:
`|\\<\\?|\\<%| is equivalent to |\\<|  and will return hits on all instances of \<`

==========
This is one of my photos.  It fails the security check, due to a match on fws\x06:
![3e53beb4-f879-11e6-9bbf-8f69aade5454](https://cloud.githubusercontent.com/assets/23568484/23235264/bc84caea-f909-11e6-8136-5887b63dbed0.jpg)

**Comment by Vekseid** [comment]
I tried to convince the SMF team to kill this stupid thing way, way back.

It was sort of relevant back in the day where not properly configuring php was a thing, along with old versions of IE checking to see if pictures could run javascript 'just in case'... which a good server admin shuts off anyway.

**Comment by Spuds** [comment]
Thank you for the sample image and details.

That security regex is known to cause the occasional (and maybe more now) false positive.  Re-encoding the image is not always effective either .. https://www.idontplaydarts.com/2012/06/encoding-web-shells-in-png-idat-chunks/

I'll have to do some more reading and see if there are other techniques that can be used to prevent the issue, as frankly the regex approach in place is about as un-intelligent an approach as one could pick.

@Vekseid so your recommendation is to simply drop it?  I was going to read around and see if it was still a relevant attack vector these days.

**Comment by Vekseid** [comment]
<% is depreciated and being removed - we don't even support it. <? is highly discouraged, and off by default. html, body, and eval are not going to do anything on their own. The flash header check, well, it's already depreciated in many browsers.

Between them, though, the non-extended checks will show up in every ~60 megabytes of compressed data. The extended ones in every 32kb. 

If you must, just block script and <?php

**Comment by sbulen** [comment]
If they were trying to get rid of <? and <%, then that regex is incorrect.

**Comment by sbulen** [comment]
FYI - 'script' matches 'description' which is found in the exif a lot.  I haven't yet seen a hit on the pattern 'script\W', which is used in checkImageContents.

**Comment by Vekseid** [comment]
The regex is correct. \\ converts to \ in the string. To actually represent a regex \ in php you need to type \\\\

**Comment by Spuds** [comment]
You beat me to it 😃 yup the regex is correct, thats how you find <? or <%

**Comment by sbulen** [comment]
I stand corrected...   Thanks!   
(That's what I get for testing with online regex checkers...)

**Comment by Spuds** [comment]
Testing the supplied image on ElkArte, it does not get flagged as bad using the normal checks (but will on the useless exhaustive / paranoid tests.) ... 

I had made some tweaks to the regex several years ago https://github.com/elkarte/Elkarte/commit/527c0af6c7c4252d958f6179055aa4c4b59fa10c 

However based on the above info we should consider further changes.

**Comment by sbulen** [comment]
These should get you hits on 'body' and 'html':
![davidprom-20170120-00001](https://cloud.githubusercontent.com/assets/23568484/23241706/76a39bc6-f929-11e6-8498-cd820866ae91.jpg)
![davidprom-20170120-00003](https://cloud.githubusercontent.com/assets/23568484/23241707/76b5cc9c-f929-11e6-87b6-c94228d6a118.jpg)

**Comment by Spuds** [comment]
Nice :bowtie:

**Comment by sbulen** [comment]
I could see where your regex look-behind doo-dad will make it more restrictive on the fws match.  That's good.  

Yep.  Good fun.  I drove these two GDIs (gosh-durned-independents) to their winter formal on 1/20/17 (remember that date?) across San Francisco thru massive protests.  They're not gonna forget that one!  I may have aged a bit driving thru the chaos, tho...

**Comment by Spuds** [comment]
Why that was the National Day of Patriotic Devotion !

As a start it seems we can drop the html and body flags or loosen it up to look for those but only with the leading < or &gt as well?

**Comment by sbulen** [comment]
Probably better questions for @Vekseid .   I'm still not sure which set(s) of code we're trying to detect...  

I must admit I'm just learning as I go here...  

Everything I've read suggests the best solution is to re-encode.  I think the full-file-scan for ANY text string has the potential for a false positive.  Again, it's all statistics.  The monkeys with the typewriters.  If there were a way to scan the non-"pixel" data, that's where I think the preg_match stuff should go.  

In an ideal world, it feels like we need to find a way to break images up into chunks, keep the "pixels" chunk, and toss everything else.  Looking at it that way, it sure feels we could do it lossless, right?  Clearly easier said than done with the tools at hand, though.  

You know it's been done, though.  I'm sure the folks at Flickr have logic to do EXACTLY that...  Amazing quality, and full EXIF retention, designed for photography junkies.

**Comment by Spuds** [comment]
It should be easy to separate the exif data from the rest or the image without doing a reencode (which will loose some quality and in GD's case loose the exif as well)

I'm not sure if its only the exif data that needs to be scanned?  If so you could scan that and if good, add it back, and if bad, discard it.  Perhaps @Vekseid knows ?

**Comment by sbulen** [comment]
I was using EXIF as the most obvious example.  

This is the best article I've found.  It focuses on EXIF.  I just noticed that the commenter actually points to your article as an example of a non-EXIF exploit:
https://www.trustwave.com/Resources/SpiderLabs-Blog/Hiding-Webshell-Backdoor-Code-in-Image-Files/

**Comment by Vekseid** [comment]
Unless someone actively enables short tags, the only way to get code executing on the server is to insert <?php

Which is going to require 32 gigs of compressed data to find randomly.

Everything else in that regexp is for client-side exploits, which requires the server admin not to turn off MIME sniffing, and for the user to be running Internet Explorer with it on. This is not a common scenario. And there are ways around every filter presented in that list. And if someone is going to attack an Elkarte/SMF forum in this manner, they will know how to get around it using e.g. onload, etc.

**Comment by emanuele45** [comment]
Just a random thoughts: the setting is named "paranoid" for a reason. ;)
http://php.webtutor.pl/en/2011/05/13/php-code-injection-a-simple-virus-written-in-php-and-carried-in-a-jpeg-image/

**Comment by Spuds** [comment]
After doing some more reading, re-encoding is not a real solution, there are examples and instructions of how to create png, jpg and gif files with basic exploits that at least survive GD's encoding.  

Funny thing is that if the system detects an "bad" file, and you have "re-encode" enabled, it will attempt to do just that and when done  it assumes the file is fixed!

I ran a sample file through the system (paranoid) it was flagged, re-encoded and saved.  The saved file still had the exploit LOL.   I did the same thing with client side xss and at least with imagick installed the exif data is retained, so after the re-encode the file is still "infected".  Classic 🙈 

The ones with server side exploit are only picked up in the paranoid check since Elk will not execute, include, or leave them discoverable for use, so worrying about it really is paranoid.  On the client side stuff we always set the mime headers and send the nosniff header to prevent supported browsers from doing MIME-type sniffing and then doing the wrong thing.

So seems neutering the current regex to the bare minimum is safe and doing a couple of tweaks to the reencode stuff would be good.   I'd move this to RC2 milestone when we have that open.

**Comment by sbulen** [comment]
Makes sense.  Thanks for the insight!  

As long as photographers don't have to play roulette with their uploads.  

FYI, I use Photoshop Lightroom CC, the current version ("Adobe Photoshop Lightroom 6.8 (Windows)").  Not sure why that 3.0 reference is buried in there, it likely references an internal standard set back in 3.0, like color palette or something...

**Comment by sbulen** [comment]
@vekseid  - can we reduce odds further, by lengthening the string?   Eg, with a space?   (Or were you assuming that already?)

**Comment by Vekseid** [comment]
For blocking <?php ? No.

What should be done is have blocking <?php be the paranoid check, and allow people who have set up their server properly to disable it.

**Comment by emanuele45** [comment]
I have mixed feeling about this.

First let's do a bit of history.
Why do we have these check in place to begin with?
TBH I'm not entirely sure, at the time I don't think I was (yet) using SMF, so I can only guess.
Back in the days of 1.x and 2.0dev, images were stored in the attachments directory with their original name. Of course this solution was open to almost any kind of possible attacks: upload a file, point the browser there and happy hacking! :tada: 
At a certain point (SMF 1.0.17/1.1.9/2.0RC1.1), the situation was "discovered" and a series of fixes were introduced, one of them was a preg_match on the content of the image. The other was hash the name of the files making them virtually inaccessible from the web.

Lesson completed, fast forward to 2017.
Is the check really that useful?
If I have to say the truth, when I started writing this I was leaning towards the "keep it", but while writing and doing some research, I think I moved towards the "it's completely pointless" side.

The preg_match addresses a very limited subset of possible attack vectors, likely the ones familiar to the developers at the time and the easy ones to detect (and maybe the ones that were used when the bug was first discovered, who knows), but that in fact cannot do much against a plethora of other attacks, much more problematic (see [imagetragick](https://blog.sucuri.net/2016/05/analyzing-imagetragick-exploits-in-the-wild.html) as an example) and difficult (or almost impossible) to detect that we are going to miss.

As such, it's almost like test our food for arsenic and thinking that it's enough to detect any possible kind of poisoning we could face (including cyanide).


> <% is depreciated and being removed - we don't even support it. <? is highly discouraged, and off by default. html, body, and eval are not going to do anything on their own. The flash header check, well, it's already depreciated in many browsers.

If something is deprecated doesn't really matter: as long as it can be used and could be a vector of attack, it **is** a risk.

> Between them, though, the non-extended checks will show up in every ~60 megabytes of compressed data. The extended ones in every 32kb.

Is this based on the assumption that compressed data are randomly distributed characters?

**Comment by Vekseid** [comment]
> Is this based on the assumption that compressed data are randomly distributed characters?

It's not the best assumption, but here is one of my avatar directories:

    grep -lU "<%" * | wc -l
    1733
    grep -lU "<\?" * | wc -l 
    7529

This is out of 7532 user-uploaded avatars in this specific directory (I have another upload directory).

It was ridiculous. Anyone who claims it wasn't did not bother even checking.

**Comment by Spuds** [comment]
> As such, it's almost like test our food for arsenic and thinking that it's enough to detect any possible kind 
> of poisoning we could face (including cyanide).

And in our case we offer an arsenic cure that does not even work.  Take this pill and it will remove all of the arsenic from your system .... oh sorry, guess it did not work 💀 

> This is out of 7532 user-uploaded avatars in this specific directory 

Very interesting ! ... now I need to go do the same test !

**Comment by sbulen** [comment]
Two stupid questions:
1 - How do you get this code to actually execute?
2 - What is the nature of that c/fws<bin> exploit?

Thanks for humoring me...

**Comment by sbulen** [comment]
I suspect the high count of "script" is part of the "description" tag in the exif, not the script\W.   

I'm still wondering what an airtight and appropriate solution is...

**Comment by emanuele45** [comment]
Spuds wrote on 26/02/17 04:00:
>
>  >   As such, it's almost like test our food for arsenic and thinking that it's enough to detect any possible kind
>   >  of poisoning we could face (including cyanide).
>
> And in our case we offer an arsenic cure that does not even work. Take this pill and it will remove all of the arsenic from your system .... oh sorry, guess it did not work 💀

Sounds like homoeopathy! :grinning:

**Comment by Vekseid** [comment]
@sbulen 

> What is the nature of that c/fws exploit?

It's for catching attempts at uploading flash files.

**Comment by sbulen** [comment]
Is the eval string still dangerous, or part of the older IE set, & not really applicable today?

**Comment by Vekseid** [comment]
I think it's supposed to be a catch-all for some nasty javascript and php tricks.

**Comment by emanuele45** [comment]
Was that last commit a fix for this?
Can be closed?

**Comment by Spuds** [comment]
Yes .... can be closed.  Could consider using it in 1.0.11 but not necessary by any means.
