### ISSUE TITLE
Checkbox agreement should allow for language selection

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2892]

**Comment by emanuele45** [comment]
Can be moved to RC2 or do you plan to fix it?

**Comment by Spuds** [comment]
I don't think I'd fix it for RC1 .... will see if its easy and if so I can add it in with the D&D Select Them PR

**Comment by emanuele45** [comment]
I was looking into that one.
At the moment I have two options:
1) use AJAX to load the "other" language of the agreement (because being at the end of the page, I would expect the wannabe use to fill in the password and **then** select a different language, and a reload of the page would wipe the form,
2) remove the text and open a new window with only the agreement (even facebook does that, so it may not be **that** bad).
With 2 we would even add an overlay popup if js is enabled so that it doesn't move the user away from the page.

**Comment by Spuds** [comment]
I'd kind of lean towards 1 but I'm old school!
