### ISSUE TITLE
login redirect

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#2902]
If you guest and you login the site from the address .../index.php?action=post;topic=123.0;last_msg=456 , you will be transferred to the address .../index.php?action=jslocale;sa=sceditor

**Comment by emanuele45** [comment]
Can we learn from google and stop using the session for that?
Can we pass the url as GET or POST parameter of the form? :angel: 
Pretty please, with sugar on top, and two :cherries: too. :laughing: 

On the serious note, passing explicitly the current URL to the backend I feel it may e easier to deal with, also because we wouldn't have to let php guess where the user wants to go back, but it will just be the user to tell that to php.
I guess we can do it with javascript or rendering the url in an hidden field. Something like that.

The other option is to make the login fully ajax based. That would work as well, but we'd have to think about error pages that currently show a login form and should instead provide an error and an ajax based login form. But it shouldn't be terribly difficult as well.
