### ISSUE TITLE
Session_write_close()

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2933]
PHP 7.1, this is with ElkArte 1.0.10 but I'd suspect it will happen with 1.1 just as well

```session_write_close(): Failed to write session data using user defined save handler. (session.save_path ...)```

The error "reason" is just some default that PHP pumps out, the session path is just fine.  I **only** see this error occur (a few times a day) and only on an XML requests such as ```?action=dlattach;topic=123.0;attach=456;image```

I'm thinking its due to a member clicking on an image thumbnail (duh) to expand it, but the session being expired.  Thats an I think only  since its only happens a few times a day.

**Comment by emanuele45** [comment]
Doing a search in google, I found this bug report at Symfony:
https://github.com/symfony/symfony/issues/17845

So I had a look at how they deal with the database session handler:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php#L322
it doesn't differ too much from ours: they try an UPDATE, if that doesn't work try an INSERT and if in certain conditions this fails, they try again an UPDATE.

The error should pop up because the write method returns false.
There are a couple of situations in which it returns false:
  1. if the session id doesn't respect the format ```~^[A-Za-z0-9,-]{16,64}$~```
  2. if both insert and update fail.
I'm tempted to ask: why do we check the session id format?
It already changed in the past, and now it seems it can be up to 128 chars, so that may be one reason, but I think it's unlikely.
The other option is that the db actually fails to write the session. That's even more difficult to imagine the reason... :confused: 
What about just return true? :angel:

**Comment by albertlast** [comment]
why you not try smf 2.1 style? 
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Db-mysql.php#L69

**Comment by Spuds** [comment]
It could be that session_id check.  I'll add an additional logging statement there and see if that is what triggers it to return false.

**Comment by emanuele45** [comment]
As suggested by the changes made to 2.1, it may very well be the session **is** written correctly, but since the data before and after are exactly the same, the update and insert both return 0 affected rows.

I'm not entirely sure change MYSQLI_CLIENT_FOUND_ROWS is "nice", because if it affects the return of mysqli_affected_rows as well, it may introduce some other issues (e.g. log_floodcontrol, etc.).

That was originally the reason I introduced a microtime in the session, just to be reasonably sure the session data was always different. But maybe this is not enough.
You may try to change:
```
$_SESSION['mictrotime'] = microtime();
```
to a random hash.

**Comment by Spuds** [comment]
Validated that its not due to the session id check so i'll try a different hash algo to see what that does.

**Comment by albertlast** [comment]
two reason why you should do this:
- less io/garbage on db side
- to get align with postgres, because ther is this behavior default (dunno if you can change this)

**Comment by Spuds** [comment]
I changed from microtime to something with more entropy and that reduced the number of occurrences say from 1 or 2 a day to 1 or 2 every few days, so a good improvement.

The error appears to be triggered on a lazy load image, the page loads, then the JS starts and swaps data attribute data to the src tags, I'm not sure why that forces the issue, but that appears to be the genesis, at least for this specific  issue I'm seeing..

Changing to CLIENT_FOUND_ROWS is something we should consider for 2.0, ... IMO its to late for 1.1 and scary for 1.0.  We could use mysqli_info to see if rows were found but not updated, but I'm not sure what the abstraction layer is returning for postgre updates ... if in fact it is the number of found rows vs changed rows then we could possibly add a return value for UPDATE in the mysqli layer and act on that for this specific issue :/

So ....
1) more entropy "forces" the update to run and return true 99% of the time, of course its also forcing an update that is not always needed. 
2) drop the microtime and use insert replace instead of insert ignore should the update fail.  This should have the same effect as the microtime, meaning if the session id exists we will get a true result.
3) 1 and 2 if we feel the update is failing  a substantial % of the time (contention / race / other / PHP meddling) this would be better than 2 alone (thinking updating an existing is more efficient than the delete insert)
4) drop microtime and just return true ... failure here does not really mean all that much, we don't act on it AFAIK.

**Comment by Spuds** [comment]
I tested #2 for most of the day and no errors were logged.  Now I'm testing number #4
