### ISSUE TITLE
NoFollow Attribute on all external Forum Links: How does it work?

### ISSUE THREAD

**Issue by ghost** [elkarte/Elkarte#2969]
Hello Developers,

I usually use Github Issue Tracker to bring my CMS/Forum-related questions. I would like to know how I can convert ElkArte to noFollow. For example, I currently have all outgoing forum links with the noFollow attribute.

How can I achieve this?

Thanks in advance.

P.S. A noFollow plugin I have not found so

**Comment by emanuele45** [comment]
There is an addon attached to [this topic](http://www.elkarte.net/community/index.php?topic=3334.75) but read it all, because there are two fixes that were not applied to the code yet.

This will change (almost) all the links posted by users in posts (and signatures?) to nofollow (and there is some control with permissions to decide if users can post without nofollow).

Not sure if this is what you were thinking about.

**Comment by Spuds** [comment]
Feature added here: https://github.com/elkarte/Elkarte/pull/3783
