### ISSUE TITLE
[1.1 RC2] E-mail activation is not functioning

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#2990]
I'm trying to puzzle out what's wrong. There appears to be a pointless hash, but it doesn't matter because the code input is for some reason not even getting returned from getQuery.

**Comment by Vekseid** [comment]
Derp. I see what's going on.

The pointless hash blocked the activations initially. Because getQuery does not check POST variables, it can't verify a manually entered code.

Not sure why the hash is there, but either way this is an easy fix.

**Comment by Vekseid** [comment]
So this is actually three bugs.

- The 'unhashed' value only gets sent out during the original registration message. It is impossible for an Elkarte user to activate their own e-mail if they do not get this message.

- It is impossible for an Elkarte user to manually input their code because the Elkarte side only checks for get variables, not post.

Oi.

Why the hash in the first place?

**Comment by Spuds** [comment]
Is it just the manual entry of the code that you are having a problem with?  I just tried the normal registration flow and used the activation link in the email and it worked as expected.

**Comment by Vekseid** [comment]
@Spuds manual entry does not work, nor does it work for 'reminder' emails that get sent after the initial one.

If a user does not get the initial e-mail, as I said, it is impossible for them to activate their account in Elkarte because what is getting sent to them is the raw verification code, not the pre-hashed token.

**Comment by emanuele45** [comment]
hmm... I'm a bit confused... but that's not unusual. :laughing: 

What I tried:
1) I went to elkarte.net in a private browser window and registered,
2) I ignored the first email, tried the login and asked for a new activation email,
3) I went to the activation page inserted the code,
4) got nothing
5) followed the link and the account was activated.

I see two problems and one bug.
The bug is: the _activate_validate_code function checks GET, but the form sends POST. My proposed solution: change the form to send GET. *Do note*: _activate_resend does getPost on code, so it may be necessary to change that as well, but I'm not sure.

The two problems are:
1)  the activation page doesn't show any error, it just reloads (at least in this case where the code was provided via POST instead of GET), honestly it's probably not that easy to generate an error, because the page seems to just return in most of the cases;
2) if the user doesn't receive the activation email, the only way to get a new one is (I think) try to register a new account, maybe we could track the registration (actually we already track it in the session I think or in the cookie) and show a gentle reminder along the lines "You have just registered, if you did not receive the activation email please click here." I know it's not reliable, but I feel it could help.

@Vekseid 
> The 'unhashed' value only gets sent out during the original registration message. It is impossible for an Elkarte user to activate their own e-mail if they do not get this message.

This is intended, but if you ask a new activation email, you get an entirely new code, so I don't see the problem here (unless you think the only way for you to let someone activate their account is for you (admin) to go into the database and get the activation code, that of course is not the way it is supposed to work :wink: ).

**Comment by Vekseid** [comment]
Hmm. Try the e-mail from 'remind and send e-mail' via the admin menu? That one isn't resetting the code.

**Comment by emanuele45** [comment]
On a quick look it should:
https://github.com/elkarte/Elkarte/blob/84535f27ef8f25c51c7e3c76dcf2536c454a4813/sources/admin/ManageMembers.controller.php#L1297
but I guess I have to try it again with an actual registration. **nods**
