### ISSUE TITLE
Users who can't use PMs still have send PM options shown to user others

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3031]
https://www.elkarte.net/community/index.php?topic=4731.msg34183

**Comment by emanuele45** [comment]
I tried these combinations:
1) denied "read" denied "send" => no trace of the buttons
2) given "read" denied "send" => menu entry with "read messages" still accessible, no trace of "send"
3) denied "read" given "send" => the menu disappears but the send in the "mini profile" appears

Number 3 is slightly odd, though it's also an odd configuration to begin with, the only thing I can come up with is some check that specifically disable the "send" permission if the "read" is not set.

**Comment by emanuele45** [comment]
Okay, more details: the issue is that when a member cannot read PMs, any other member that can send PMs will still be able to send that user a PM.
So:
* User A has permission to read and send PMs
* User B does **not** have permission to read PMs
* User A is still able to send PMs to user B

As such, it is not a bug, because the behaviour has been like that since the beginning, so => feature request

Now, on the feature matter, I **think** the idea behind this behaviour is that admins sometime use to remove the read PM permission to for example banned members, and if other people would not be able to send them PMs, the status would be somehow revealed.
That said, I'm neither in favour nor, against the change, to me it's the same (especially considered most admins are actively searching for ways to mark the banned members as such).

**Comment by Spuds** [comment]
Going to close as will not implement
