### ISSUE TITLE
 The function elk_seed_generator() has been deprecated.

### ISSUE THREAD

**Issue by live627** [elkarte/Elkarte#3077]
see https://scrutinizer-ci.com/g/elkarte/Elkarte/inspections/5c8b3d7e-299e-4444-a5ef-f26246a2359d/issues/files/bootstrap.php?status=new&orderField=path&order=asc&honorSelectedPaths=0&issueId=26297345#inspectioncomment-94366456

Is there a replacement?

**Comment by emanuele45** [comment]
I guess I missed a bunch of stuff in my remove-the-deprecation. :laughing:

**Comment by live627** [comment]
but does it not serve a purpose? Was it tied to old password hashing?

**Comment by Spuds** [comment]
I think it was only used for validation codes but is now no longer used.

**Comment by emanuele45** [comment]
I had to revert the removing of the function because apparently postgre doesn't ends the tests unless there is the function in place.
It doesn't serve almost any purpose, but without it postgre apparently doesn't deal properly with sessions (at least that's my feeling).
If you have any idea feel free to try to have a look, I'm giving up for now.

**Comment by live627** [comment]
There was 1 failure:

1) TestAuthsubs::test_login_cookie

Failed asserting that null matches expected 1.

/var/www/tests/sources/subs/Auth.subs.Test.php:42

https://travis-ci.org/elkarte/Elkarte/jobs/317790625

**Comment by Spuds** [comment]
> If you have any idea

MySQL Only ... stop the postrre pain

**Comment by Spuds** [comment]
Removed long ago in 2.0
