### ISSUE TITLE
IE wrongly align BBC links

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3153]
https://www.elkarte.net/community/index.php?topic=5071.0

In particular reply 3 and the image:
<img src="https://www.elkarte.net/community/index.php?action=dlattach;attach=5590;image" />

**Comment by Spuds** [comment]
this appears to be due to the inline-block and overflow:hidden ..  The intent of the current css appears to not allow a link to be more than one full line of text.  We would have to target the bbc_link text inside of a message body with some bottom margin (since it behaves differently in signatures etc)  .... or simply remove most of that css and just allow a long link to flow naturally (with a break-all) in the text.
