### ISSUE TITLE
Custom message icons appear as default icon (XX) on the message index

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3170]
https://www.elkarte.net/community/index.php?topic=5186

**Comment by Spuds** [comment]
@emanuele45 please take a look at this and see what you think.   There are a few other calls to ```new MessageTopicIcons()``` in the code that would potentially need updating so this is for review of the approach.

**Comment by Spuds** [comment]
Oh bother ... I guess 1.1 still supports 5.4 ?  If so need to replace that call to array_column with some other foreach nonsense 🚽

**Comment by emanuele45** [comment]
Looking at the old code (before I managed to break it) I'd say I misinterpreted it.
In an attempt to eliminate some checks that seemed redundant (i.e. the file_exist) I completely changed the logic... :-\

Originally, the "display" part was not **really** loading the icons, it just grubbed anything thrown at it and if a check was not explicitly required, then it was going to display the icon even if it was broken.

Now, I changed so that if the icon is not loaded the default one is displayed.

One way to restore the previous behaviour is:
https://gist.github.com/emanuele45/927a4e4928e8610035473e47b6f4ffa6

**Comment by Spuds** [comment]
I think we are on the same track ! 

I did this https://github.com/Spuds/Elkarte/commit/388d21fd69cfe529518b0863296f62947a01ad2e which is pretty much what your gist showed with 2 minor changes.  

One was I broke one method into two and the other was I still allowed the custom array to be passed which the topic listing can use and allows a single call to load them all.

Still have to fix the 5.4 thingy ...
