### ISSUE TITLE
Upgrade script spot checks the wrong file

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3175]
The 1.1.3 upgrade script has an error due to the spot check we do to make sure the upgrade script and files are compatible.   The version of the upgrade script is defined in installcore.php ... so for 1.1.3 it sets 
```CURRENT_VERSION = '1.1.3'```

Next we check one of the files and historically it has been index.php.   This involves reading the comment header where we look for the @ version tag and compare that value with what CURRENT_VERSION.  This results in ```1.1.3 vs 1.1.1``` because index.php has not changed since 1.1.1.

Historically index.php always changed with each new revision since the forum version constant was set in that file, but in 1.1 we moved that setting to bootstrap.php.  So what does that all mean?  Basically we need to read bootstrap.php and not index.php going forward.  In the upgrade.php script we need to make the following change.

```
	// Do a quick version spot check.
	$temp = substr(@implode('', @file(BOARDDIR . '/index.php')), 0, 4096);
```
To 
```
	// Do a quick version spot check.
	$temp = substr(@implode('', @file(BOARDDIR . '/bootstrap.php')), 0, 4096);
```

**Comment by NegativeIQ** [comment]
A small note, its not just upgrade script (i think). I just forked and cloned Elk. Set permissions to 777 since its my local machine and i dont care about setup thats gonna be nuked 100x times. After copying and renaming sample files and finishing install i checked to delete install files. Opening elk just redirected me to upgrade php file (that did not exist). So i had to manually delete install directory itself. (Note permissions are at 777 for everything)
