### ISSUE TITLE
Error in checking file syntax

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3215]
Our syntax checker is failing on blackhole.inc.php due to an inline xxxx {$xxx} xxx construct.    Filetest basic does a 
```
				// This is for variables in strings "something {$a_variable} in a string"
				elseif (is_array($token) && $token[1] === '{')
					$level++;
```
This is failing to do the increment, where as the below does.   
```	
				// This is for variables in strings "something {$a_variable} in a string"
				elseif (is_array($token) && strpos($token[1], '{') !== false)
					$level++;
```
Not sure if there are other side effect as well or if this is the best way to count the {} tokens.   Also this effects the DataValidator class as it uses the same type of syntax check.

**Comment by emanuele45** [comment]
Interesting...
Just for the record, the actual line failing is:
```
$result = gethostbynamel($settings['httpbl_key'].".${find}.dnsbl.httpbl.org.");
```
because ```${``` is considered a single piece and presented as:
```
Array
(
    [0] => 385
    [1] => ${
    [2] => 4
)
```
I'm not sure if this is the best way to check the syntax, I only came up with it while trying to find a way able to detect syntax errors without actually execute the code (that is usually a pain in the arse).
A possible workaround for the specific case is change the if to:
```
	if ($token === '{' || (isset($token[1]) && $token[1] === '${'))
		$level++;
	elseif ($token === '}')
		$level--;
```
