### ISSUE TITLE
ip instead url site

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#3245]
I sometimes have this kind of garbage, maybe it's just me.

elk - 1.0.10
PHP - 7.1.19

![stupid](https://user-images.githubusercontent.com/2246621/46571698-65768e00-c982-11e8-9ac0-24e4f43507f5.png)

**Comment by emanuele45** [comment]
And again I didn't get notifications about issues... :-\

hmm... The interesting thing is that at least for 1 of the URLs, the domain is properly displayed.
It seems like at a certain point, some code replaces the correct url of the theme with the wrong one.
Do you have addons installed?

**Comment by interlab** [comment]
recently the error has disappeared. I think that at php the flag of global replacement sometimes falls off.

**Comment by interlab** [comment]
installed mods:
Bookmarks
Fancy Box 4 ElkArte
FlarumStyle
HTML BBCode
HTML5 Video Audio BBC
Recent Topics
Spoiler Modern

**Comment by Spuds** [comment]
I know this is an old topic, but I have seen this on one of my servers, and its only (1) site of (5) that ever does the FQDN -> IP address swap ... which then causes the site to display as a mess since the style sheets are missing.

The "culprit" here seems to be `function loadThemeUrls()` which uses `$_SERVER['HTTP_HOST'] and $_SERVER['SERVER_NAME']` for checks, neither of which are really that trustworthy.

TBH I'm not sure why that function is there, maybe it was intended if you mis-entered theme details in the admin panel?  The www redirect is understandable but the rest?

Anyway I think one of those `$_SERVER` values gets loaded with the IP, this is not an ElkArte issue but something on the server or the server site control panel.  I've only seen this on ispconfig and then only on the first site defined in that panel.  Never seen it on the other sites.

In that function you can add after `		$detected_url .= empty($_SERVER['HTTP_HOST']) ? $_SERVER['SERVER_NAME'] . (empty($_SERVER['SERVER_PORT']) || $_SERVER['SERVER_PORT'] == '80' ? '' : ':' . $_SERVER['SERVER_PORT']) : $_SERVER['HTTP_HOST'];`  
the following:
```
		if (strpos($detected_url, 'mydomain.com') === false)
			$detected_url = 'https://mydoman.com';
```
which simply prevents the IP address from propagating past that point.  Yes leave off the www,  otherwise site based www redirection will not work.  and of-course `mydomain.com` is your real site name.

perhaps updating that so it uses the boardurl as a check ....

**Comment by Spuds** [comment]
Also it may work to change 
`			if ($do_fix === true || preg_match('~^http[s]?://(?:[\d\.:]+|\[[\d:]+\](?::\d+)?)(?:$|/)~', $detected_url) === 1)`
to be 
`			if ($do_fix === true)` to avoid "fixing" things should the detected url be an IP address and the board URL not being one
