### ISSUE TITLE
How does hasResults() work?

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3348]
@emanuele45 While doing my troll ... I'm not clear on how DB  -> hasResults() works.   For example one query has the following in ```$this->result``` 
```
public 'current_field' => int 0
  public 'field_count' => int 1
  public 'lengths' => null
  public 'num_rows' => int 0
  public 'type' => int 0
```
Which I believe means no results found, but ```hasResults``` will be true since $this->results is not empty (its an array or object).  Should it also be checking for empty num_rows in $this_results if it exists?

**Comment by emanuele45** [comment]
hmm... that one is intended to check if there was any error with the query: if it failed for any reason it returns false, otherwise true.
The property "result" is the return of mysqli_query.
I added it because in several places it is used to check if temporary tables are created.
I think it is misused in getTimeLastMention, attachment_folder, attachment_filesize and probably in ssi_boardNews and action_databasePopulation though they were done like that even before... :confounded:

**Comment by Spuds** [comment]
That makes sense, its the one in getTimeLastMention that I'm looking at since that throws an error as in my case the result set is empty.  I'll drop it there and just use ->fetch_row ..... wonder if we should change the hasResults to another name since its kind confusing, something like ... ummm well something better, I just don't know what that is :D

**Comment by emanuele45** [comment]
Yeah... I should check the logs, though I guess I replaced 1:1 what was there in the past.
I'm not sure why we should check in these functions if the query has failed... but that was the case... :roll_eyes: 

Regarding the name... ehm... you know the drill. :stuck_out_tongue:
