### ISSUE TITLE
SMF 2.0.16 - Auth secret

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#3381]
There are a few 2.0.16 things that could be carried over nicely I think, but this is borderline critical.

**Comment by Spuds** [comment]
I have not looked at it so don't even know what was done ... @emanuele45 have you seen this?

**Comment by emanuele45** [comment]
A "Settings.php"-specific (random) salt value was introduced to hash (with sha1) the password when stored in the cookies (along with the user-specific salt).
In Elk what we do is use the user-specific salt and sha256.

**Warning**: I'm not a security expert, so whatever I say from here on may be wrong.

Provided that anything helps in terms of security, I'm not really sure how much this adds to the mix.
If an attacker steals the cookie, whatever the salt or the hash are, he will be able to use it "as such" (being that the scope of the cookie to begin with). If we want to change that behaviour, then I think we should include either the IP and/or the browser user agent to the "salting", even though this may add some unwanted side-effects.
If the issue is the fear the cookie can be cracked and the hashed password (that would the require another round of cracking to obtain the actual password that is encrypted with... depends on the system, see PasswordHash for details) be extracted from it, I think I would favour a stronger encryption algorithm rather than an additional salt.

Again, I'm not sure what I say is correct.

**Comment by Vekseid** [comment]
@jdarwood007 would probably have better details as to what happens in SMF specifically.

I did work out that, on Elliquiy, someone could crack another user's password every few months or so, by choosing a user at random and testing the most common passwords 8+ characters long. This would generate surprisingly little attention, simply because my forum is active enough that it would absorb it. This is purely down to the 16 bit password_salt, however, it's not a fault of the algorithm itself.

IP salting is generally bad (and not remotely going to work for mobile users), and some browsers change their UAs extremely rapidly. Some ISPs will intercept and play with the UA in non-SSL connections, which is extremely frustrating. 

We could use ASN salting, though that may frustrate people who switch from mobile to home networks often. Could be an option, especially for admins, and ASN tracking is very useful for dealing with spammers en masse.

For my own project, my idea was to have the user's side spend the computational effort of hashing 256+ times. You'd then has it with an in-database salt a few times, using that as your cookie. This would block users of browsers like Opera Mini, however, which only can use a very limited subset of Javascript.

**Comment by joshuaadickerson** [comment]
So... nobody here is a security professional. Yet, we're talking about hashing algorithms and salt to "stop" an attacker from stealing the password out of a cookie. Hmm... it seems like the answer is simple: don't put the password in the cookie.

**Comment by Vekseid** [comment]
@joshuaadickerson well if someone wants to submit a PR to incorporate a login token table, and use that for verification instead, I'd certainly have no objection.

It's just easier to either adopt SMF's solution or extend the post-login salt to 64-128 bits so this attack is no longer feasible.

**Comment by Vekseid** [comment]
Well this is addressed nicely by @Spuds PR so will just close this.

**Comment by joshuaadickerson** [comment]
@Vekseid which PR?
