### ISSUE TITLE
Creating Topic via email - Detecting and separating a mail message in headers and body

### ISSUE THREAD

**Issue by JoergPalmer** [elkarte/Elkarte#3396]
**File / function:**
`EmailParse.class.php:327 / _split_headers()`

**Problem:**
The function tries to detect beginning and end of the header section by using regular expressions. The problem is that this function is called recursively for parsing the sections of a multipart message. The sequence is: 

1. for the whole message
2. for first section 
3. for second section
4. ...

As a matter of fact, when called for a section, this will never include a header. Hence the existing code will always return without filling the body block, since this is done by the second regular expression that fills the reg exp result in the $match[] array.

**Solution:**
Just delete / comment the header start check:
```
// Do we even start with a header in this boundary section?
// if (!preg_match('~^[\w-]+:[ ].*?\r?\n~i', $this->raw_message))
// {
// 	return;
// }
```

**Comment by Spuds** [comment]
I think its fine to remove that check block.

Looking at the code it should only be going recursive when it finds boundary sections, it then "expodes" those sections and does a trim, so that boundary section *should* start with a header at that point.  At least its working on a well formed message.  Of course there are lots of less than well formed emails and thats what makes email such a difficult beast.
