### ISSUE TITLE
Followups Not Working

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3497]
**Describe the bug**
Use "more" dropdown and select "quote to new topic".

You are redirected to a new topic post page as expected but w/o the quoted message.  Go through the posting process and its not a followup as it should be.

**ElkArte info**
1. 2.0

**Comment by emanuele45** [comment]
I would guess I broke it at some point, so... well, let's see how long it takes for me to find the issue. :sob: 
Actually @Spuds do you remember if it was on a fresh install or an upgrade? Because I have the feeling it could just be an issue with settings not properly migrated or created in the first place during either one (or both) of the processes.

**Comment by Spuds** [comment]
I don't recall if it was a fresh install ... I'm going to say no as I generally just overwrite the old files with new and hope for the best LOL.
