### ISSUE TITLE
Warning: session_start(): Failed to decode session object. Session has been destroyed

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#3518]
**Describe the bug**
Provide a clear and concise description of what the problem is.

**ElkArte info**
1. Are you sure this is a core Elkarte problem and not caused by any addon you are using? - Do not know
2. What ElkArte version are you using? - 1.1.8
3. When did the issue start? - today when multi-uploading image files 
4. What version of PHP are you running? - 7.2.34

**To Reproduce**
1. when creating or editing a new theme, if there are unicode smileys in the attachment file names, an error occurs.
for example a symbol like this: 📝

**Expected behavior**

**Error:** Warning: session_start(): Failed to decode session object. Session has been destroyed
**Url:** index.php?action=dlattach;sa=tmpattach;attach=post_tmp_1_60a4b079f349997a0ef92255a4e63904;topic=1239
**File:** /(...)/sources/Session.php

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/2246621/136995186-f911cc19-78db-4b67-81ab-0f3dda0dc99a.png)

**Comment by emanuele45** [comment]
What type of session management are you using?
Database?
If so, I seem to remember some issues with session data becoming so big that were not able to fit into the column and ended up corrupted. Try changing in the sessions table the column data from text to something bigger like mediumtext. That could mitigate the issue (i.e. work until it reached the next limit, though mediumtext should be good enough for quite a while, I think).

**Comment by Spuds** [comment]
Is this something we should change in 2.0 (text => medium) ??

**Comment by interlab** [comment]
sessions are stored in a database.
changed the field, but the error remained.

**Comment by Spuds** [comment]
Finally taking a look at this.

What happens is that we save the file name in `$_SESSION['temp_attachments']` so we can keep track of things.  A filename with an emoji like 📝 which is 1f4dd

**Comment by Spuds** [comment]
More specifically what is happening is that in our session `DatabaseHandler` file in the write function, `$_SESSION` data has that emoji symbol and then it fails to write / read into the DB ... one fix may be to change to `utf8mb4`   

The "fix" above strips that utf8 character range from getting into $_SESSION but .that is just a 🩹

**Comment by Spuds** [comment]
A bit more looking and I'm not sure that the `serialize_handler` may not be messing up those 4 byte characters as well, not sure really.  I did a very quick test with `utf8mb4-general-ci` and was still getting some anomalies with session read/write encode/decode etc.  Anyway `mb4` has its own set of items to consider.

So at this point I think the best thing to do is 
 - move `_clean_4byte_chars` out of `db_mysql.class` (its also private) and put it in `Util` so it can be used.  That function converts 4 byte utf8 into html `&#x...;` code which will store fine in sessions / db  You can't really call that on the session data since its serialized and could break that.
 - Make a call that Util::function on `$_FILES['attachment']['name']` post `htmlspecialchar` of course so you don't `&AMP;` the result
 - profit

Other ideas ??

**Comment by Spuds** [comment]
🤷 [c4f2fd3](https://github.com/Spuds/Elkarte/commit/c4f2fd350fa0ca1239aefb217b14fbda62bea025) seems like the way to go, just not sure where else this same issue could leak in ... may consider putting in a 4 byte check, similar to entity check
