### ISSUE TITLE
Site offline?

### ISSUE THREAD

**Issue by VBGAMER45** [elkarte/Elkarte#3526]
Is there an issue with the website/hosting? Noticed it has been down for a few days.

**Comment by emanuele45** [comment]
I'd sum it up as: due to low traffic, the site was not really that useful.

**Comment by tinoest** [comment]
I’d disagree, the forum side was very useful to display what Elkarte was/is. Also contained useful information that wasn’t/isn’t available elsewhere.

To me this appears as if Elkarte is no longer active and isn’t being developed further.

**Comment by Spuds** [comment]
I can see the usefulness of a demo site ... But I felt that given the low traffic / interaction that visitors were/are turned off on the dev/support site.  

As a landing page site its fine, but as a community site, not sure it was doing the project any favors *shrugs* I think visitors finding a lifeless site will look elsewhere. 

I did setup the same home page on github: elkarte.github.io/elkarte/   We could point the domain to that and use github discussions (yes some irony there) and have a demo.elkarte.net thing ... or put the site back on line and just let it be.

Just for the record, it was my choice/actions to put the site in to slumber, as I fall in the its no longer relevant camp.  Of course I'm a crusty old prick as well, so you have that.

**Comment by tinoest** [comment]
Turning it off is fine if there is some notification to the user as to what is happening. Just having a smilie face isn’t particularly professional or useful.

At the end of the day you two are the main developers so it’s your decision. I personally it serves more use being there even if it’s inactive

**Comment by zappaDPJ** [comment]
I'm also a crusty (62 year) old prick and I think, if I may say so, you've made a mistake.

You've now got a product that you have invested your free time in which is now sitting in a stock room unadvertised and not visible on the shelf so what is the point of it?

Who is going to find you on GitHub? The installed forum was your shop window, low traffic in my opinion is irrelevant. I think you are far more likely to attract interest from something that can be seen and tried rather than offering a hidden (to the majority) download on GitHub.

Just saying :)

**Comment by Lizard11** [comment]
Hello,
I think it's a great shame that the website and support forum have disappeared. Initially I thought they were both just down for a problem or maintenance at short notice, but that it was intentional didn't occur to me.
Announcements of the closures a certain time in advance, and then on both sites and with reasons, might not have been bad. And then a reference to Github.

Users who are already using elkarte will now certainly take a look at github from time to time. But I have my doubts about new users of the forum software.
If I wanted to run my own forum for the first time and was not yet familiar with such a thing, and then searched the Internet for good software, I don't think I would choose elkarte. I would probably end up with SMF or something else. Simply because there are websites and clear support forums with lots of explanatory texts, screenshots and other pictures. That just makes a much bigger impression and looks like something much bigger than the almost only texts and codes on Github.
I think that with only one page on Github, elkarte looks small and inconspicuous on the outside. A newcomer can't see what the software can do, how extensive it is, and what finished forums can look like. In the support forum alone, you could already see a lot in this respect.
Even if new posts were not made very often in the forum, there were still a lot of interesting and helpful ones in it, which were often very helpful to visitors who perhaps only looked in from time to time to read.

So, in any case, I would love it if the website and the support forum would go back online. If the forum is to be discontinued, it could be closed and only remain online as an information page. And whoever needs questions or help with something can then be referred to github from both sides.

So far from me.
Best wishes to all and have a happy new year!
Ms. Chaos

**Comment by emanuele45** [comment]
Truth to be said, also our activity (and mine in particular) has dropped dramatically during the last year.
I'm trying to get "back on track", but personal reasons and stuff it's a bit difficult. 2.0 has been (as it seems to be the leitmotiv for SMF and derivatives) has taken its time to be developed and it's far from a stable solution (still), and I can't deny most of the stuff broken is due to my random changes along the way that I never manage to fix. :man_shrugging:

**Comment by augras** [comment]
Hi,
I agree with Lizard11 post.
The last week i worked on SimplePortal french translation (there were a lot of bad things and a lot of lake) : what can i do with the files now ?
With the site off it is not possible to add addons from the packages manager (there is no more server with the list of addons), the translations are no more accessible on translations.elkaret.net... How a new user can choose Elkarte now ?
Elkarte is a great forum and you are not a lot to work on, i understand that, but without the site all the archives are lost and a new user need to install himself Elkarte to see what it is.
I you need help for the site i can try to help.
Philippe

**Comment by tinoest** [comment]
To me that sounds like Elkarte is dead, and I’m pretty sure everyone else will feel the same. Which is a shame as it had so much promise and was a very welcoming place.

We all go through stages of increased or reduced activity. That’s life, however Elkarte will tick over in the background and I don’t see the need to remove the forums, other than to hammer the nail in the coffin and say that’s it.

**Comment by augras** [comment]
Spuds sayed
> I did setup the same home page on github: elkarte.github.io/elkarte/ We could point the domain to that and use github discussions (yes some irony there) and have a demo.elkarte.net thing ... or put the site back on line and just let it be.
> 

And tinoest sayed
> Turning it off is fine if there is some notification to the user as to what is happening. Just having a smilie face isn’t particularly professional or useful.
> 
> At the end of the day you two are the main developers so it’s your decision. I personally think it serves more use being there even if it’s inactive.

We can't stay with just a smile, i think.
A choice must be do now.

For me the site must be open : we can make a choice after.

And an "inactive" site can show that Elkarte is strong enough to doesn't need help... maybe i'm wrong, i don't really know.

**Comment by Spuds** [comment]
Some innocent soul, identity unknown, has installed and EARLY 2.0 beta version on the site and its back online for all

**Comment by augras** [comment]
Thank's a lot to that innocent soul !
And it's a goog idea from her for a test in real life Elkarte2.0... maybe not, but we will see:)
https://translations.elkarte.net/ is back also, but https://addons.elkarte.net/ is not working for me and https://themes.elkarte.net/ not more (it was already the case for themes if i remember).

**Comment by augras** [comment]
>it's a goog idea from her for a test in real life Elkarte2.0... maybe not, but we will see:)
I just tried to connect and i'm connecting but get an "Class 'ElkArte\Themes\Errors' not found" : can't do anything !

**Comment by Spuds** [comment]
That should be fixed now, that was a home page error (which is still not quite right), but if you still have problems go to the forum at www.elkarte.net/community directly

Addons and Themes were simple redirects to https://elkarte.github.io/addons/ and https://elkarte.github.io/themes/ so if you need something immediately that is where they have always been.

**Comment by tinoest** [comment]
Can this be closed now?
