### ISSUE TITLE
Like Button Hidden when AdBlock Plus has Social Media Tracking enabled

### ISSUE THREAD

**Issue by tinoest** [elkarte/Elkarte#3564]
If you are running AdBlock Plus and enable "Block social media icons tracking" the likes button is hidden. This is due to it blocking the class likes_button. Renaming to react_button or similar allows it to reappear again. 

I can submit a fix for that if you're happy to rename the class and leave likes as likes. It's a weird bug caused by some other software which is being unintelligent but is easy enough to fix.

**Comment by Spuds** [comment]
I've had that complaint in the past and also tracked it down to one of the lists in an adblock program.  I think there may even be a thread on the site, or that may just have been on the site I was helping with.  I was never sure what to rename things to in order to evade that lookup list, plus the user in question was being a bit of an 🥇 ass.    

Anyway if you have the class name that works then by all means submit the PR
