### ISSUE TITLE
Elkarte 2.0 - Quick link to Drafts under Profile

### ISSUE THREAD

**Issue by radu81** [elkarte/Elkarte#3570]
In Elkarte 1.1 we have a quick link under profile icon to go to Drafts, in Elkarte 2.0 there is no link.

![Drafts](https://user-images.githubusercontent.com/5116478/150761719-527c0c4c-cde1-4abc-82fb-925127450e5a.jpg)

**Comment by Spuds** [comment]
This one is kind of interesting.  
Drafts are a board related permission, so when you are on the main page, no board permissions are loaded.  The menu item does appear once you navigate to a board.  I could not really see a reason to have it hidden (if the feature is on and they are using it etc) simply because of what board you are on, it not like the listing of drafts is shown only by board.  If you don't have the permission it will just show up empty.

**Comment by radu81** [comment]
Yes, I confirm, if you are on a board where you have drafts the "My Drafts" menu is visible under profile. This is not intuitive, I hope you'll find a solution.
