### ISSUE TITLE
FileFunctions.php suggestion

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#3577]
File Elkarte/sources/ElkArte/FileFunctions.php

Lines 45-48 need deleted.

https://github.com/Spuds/Elkarte/blob/788079fdd92c3cface9c544e437646c7dd2c762f/sources/ElkArte/FileFunctions.php#L45

```php
			if ($this->isWritable($item))
			{
				return true;
			}
````

**Comment by interlab** [comment]
```php
FileFunctions::instance()->isDir($modSettings['avatar_directory']);
```

maybe it's better to make a static function?
```php
FileFunctions::isDir($modSettings['avatar_directory']);
```

**Comment by Spuds** [comment]
I thought about making them all static like our ```Util``` functions but ended up doing the static instance.  I could not come up with a clear reason to do one or the other. 

You can  do what you show ```FileFunctions::instance()->fileExists()``` or just assign it to a class property as ```$this->filefunc = FileFunctions::instance();```  then do ```$this->filefunc->isWritable()``` which comes in handy when you have a lot of calls in a file.

```Lines 45-48 need deleted.``` they could be moved below line 50 and save a isWritable call that was already made, but you need some way to end that while loop as soon as the lowest level chmod value succeeds, otherwise everythign would end up at 0777 or 0666 or am I missing something?

**Comment by interlab** [comment]
oops, you don't need to delete it.
so there are fewer checks:

```php
		foreach ($modes as $mode)
		{
			$this->elk_chmod($item, $mode);

			if ($this->isWritable($item))
			{
				return true;
			}
		}
```

**Comment by Spuds** [comment]
Going to leave it open until I submit the PR for the fewer checks improvement
