### ISSUE TITLE
Notify of all posts

### ISSUE THREAD

**Issue by norv** [elkarte/Elkarte#63]
Add the possibility to 'notify me of all topics, replies, in this/these board/s'.

This is a functionality we have always rejected in another world, under the (main) reason that admins won't realize the impact on shared servers.

I suggest we reconsider this: the entire discussion around it, its usefulness, its risk and possibility to mitigate it.

**Comment by emanuele45** [comment]
/me waits for the effect of the :wine_glass: to face away. LOL

**Comment by Spuds** [comment]
LOL .. I did update the way the queue works here: https://github.com/elkarte/Elkarte/pull/1197  For that to work its basically allow the system to control it.  Since its really a special scheduled task the changes allow for full use of the quota in a given time it set to "auto" which I think is 0 or something.

For example say you set it to 10 per min, and you only get one page load in that min, the old way would have set say 2, or its slice, the new way would send all 10.  If there had been 2 sent with 8 remaining in this min's quota it would send 8 If it was the last slice of the that time limit.  OK terrible description, the comments in the code are a bit better.

**Comment by emanuele45** [comment]
Then this can be close I suppose. YAY!
